name: Deploy Azure Function

on:
  push:
    branches:
      - 'main'
      - 'feature/ATA-4'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Archive the application
    - name: Archive project
      run: zip -r functionapp.zip . -x ".*" "*.venv*" "tests/*"

    # Deploy to Azure Functions
    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: a2a-speech-recognition-app-service  # Replace with your Azure Function App name
        package: functionapp.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
